### ISSUE TITLE
Please don't use MM-DD-YY (US) Date Format

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/EdgeEnterprise#38]
Please can you use a universal date format such as 2020-01-08, rather than MM-DD-YYYY?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d545c7f-5338-5cd3-0002-ae92b0f770cb
* Version Independent ID: d767304a-e328-89f5-0d4a-333447494d13
* Content: [Plan your deployment of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/deploy-edge-plan-deployment#feedback)
* Content Source: [edgeenterprise/deploy-edge-plan-deployment.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/deploy-edge-plan-deployment.md)
* Product: **microsoft-edge**
* GitHub Login: @appcompatguy
* Microsoft Alias: **cjacks**

**Comment by dan-wesley** [comment]
@ccsjnw Thank you for calling this out.

**Comment by dan-wesley** [comment]
@appcompatguy I'd say that setting the date format is way above my pay grade.

**Comment by appcompatguy** [comment]
Assuming this is referring to the header (beneath the article name, based on when last updated), that's going to use the predominant date format in the locale specified.

For example, in en-us, we have 04/23/2020, while in en-gb we have 23/04/2020.

**Comment by dan-wesley** [comment]
@appcompatguy Do the dates in the body of an article get reformatted based on locale?

**Comment by appcompatguy** [comment]
Yep. Try it!

**Comment by ccsjnw** [comment]
No, they don’t. That’s the problem. Even if they did, it’s never actually clear (for example) if 05/08/2020 is 5th August or 8th May.
Why can’t the universal format of YYYY-MM-DD be used?


Regards,
James.


T. 01482 867809
M. 07595 372748
E. james.willmott@outlook.com<mailto:james.willmott@outlook.com>

**Comment by appcompatguy** [comment]
They do for me, so that should be a workaround for now.

That being said, it's a completely righteous request. Even if we don't default to your recommendation for everyone (while many would argue that ISO 8601 is the "right way", there are just as many who would argue for regional "norms") you shouldn't have to pretend you live somewhere else just to get dates formatted as you prefer, and I don't think ISO 8601 is the "standard" date format in any locale.

Unfortunately, that's not something we control at the individual page or documentation set level.

The feedback page for the site as a whole is here: https://github.com/MicrosoftDocs/feedback/issues

It would be a great feature request to have the overall docs site support that in settings!
